on: workflow_dispatch
name: git

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        ref: main
      
    - name: Run the workflow script
      run: |
        # Make Bash print the commands as it is executing them
        set -x
        
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # Run the workflow script
        date -Iseconds > git-artifact
        
        # Stage the Git index changes resulting from the CI script
        git add git-artifact
                
        # Commit the staged changes to the workflow repository
        git commit -m "Commit generated content"
        
        # Push the commit to the workflow repository
        git push
