on: push
name: git

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Run the workflow script
      run: |
        # Make Bash print the commands as it is executing them
        set -x
        
        # Configure Git for the push from the workflow to the repository
        #git config --global user.email ""
        git config --global user.name "${{github.repository_owner}}"
        
        # Check out the `main` branch - GitHub Actions checks out detached HEAD
        git checkout main
        
        # Run the workflow script
        date -Iseconds > git-artifact
        
        # Authenticate with GitHub using the out-of-the-box workflow PAT
        git remote set-url origin https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}
        
        # Stage the Git index changes resulting from the CI script
        git add git-artifact
                
        # Commit the staged changes to the workflow repository
        git commit -m "Commit generated content"
        
        # Push the commit to the workflow repository
        git push
