on: push
name: graphql

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Run the workflow script
      run: |
        # Make Bash print the commands as it is executing them
        set -x

        # https://docs.github.com/en/graphql/reference/input-objects#committablebranch
        BRANCH='{"nameWithOwner":"${{github.repository}}","branchName":"${{github.ref}}"}'
        
        DATA='{"query":"mutation { createCommitOnBranch(input:{branch:'$BRANCH',message:\"Make a test commit using GQL\"}) { commit, ref } }"}'

        # Call the GitHub GQL API endpoint using the integration PAT token
        # https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#communicating-with-graphql
        curl --no-progress-meter -H "Authorization: bearer ${{github.token}}" ${{github.graphql_url}} -d "$DATA"
